// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Stretch Desk",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Stretch Desk",
            targets: ["AppModule"],
            bundleIdentifier: "hada.stretchdesk",
            teamIdentifier: "F3D69PH55A",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .running),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Scan your hand pose")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Flipboard/FLAnimatedImage.git", "1.0.17"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "FLAnimatedImage", package: "flanimatedimage")
            ],
            path: ".",
            resources: [
                .copy("Resources/WristStretchActionClassifier.mlmodelc"),
                .copy("Resources/WS.gif"),
                .copy("Resources/WC.gif")
            ]
        )
    ]
)
